// This file is @generated by prost-build.
/// A frame from the client to the server.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientFrame {
    /// Chosen by the client. Must be greater than 0. Every answer to the request carries the same id.
    #[prost(uint64, tag = "1")]
    pub request_id: u64,
    /// 14 is reserved for recovery after a server restore.
    #[prost(oneof = "client_frame::Body", tags = "10, 11, 12, 13, 15, 16, 17, 18, 19")]
    pub body: ::core::option::Option<client_frame::Body>,
}
/// Nested message and enum types in `ClientFrame`.
pub mod client_frame {
    /// 14 is reserved for recovery after a server restore.
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "10")]
        Hello(super::Hello),
        #[prost(message, tag = "11")]
        Open(super::Open),
        #[prost(message, tag = "12")]
        Fetch(super::Fetch),
        #[prost(message, tag = "13")]
        Commit(super::Commit),
        #[prost(message, tag = "15")]
        Ping(super::Ping),
        #[prost(message, tag = "16")]
        CloseDb(super::CloseDb),
        #[prost(message, tag = "17")]
        Proof(super::Proof),
        #[prost(message, tag = "18")]
        Delete(super::Delete),
        #[prost(message, tag = "19")]
        Changed(super::Changed),
    }
}
/// A frame from the server to the client.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServerFrame {
    /// The request_id of the request this frame answers. 0 for a frame the server sends unprompted (`LeaseRevoked`).
    #[prost(uint64, tag = "1")]
    pub request_id: u64,
    #[prost(
        oneof = "server_frame::Body",
        tags = "10, 11, 12, 13, 14, 15, 16, 17, 18, 19"
    )]
    pub body: ::core::option::Option<server_frame::Body>,
}
/// Nested message and enum types in `ServerFrame`.
pub mod server_frame {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "10")]
        HelloOk(super::HelloOk),
        #[prost(message, tag = "11")]
        Opened(super::Opened),
        #[prost(message, tag = "12")]
        Pages(super::Pages),
        #[prost(message, tag = "13")]
        CommitAck(super::CommitAck),
        #[prost(message, tag = "14")]
        Pong(super::Pong),
        #[prost(message, tag = "15")]
        LeaseRevoked(super::LeaseRevoked),
        #[prost(message, tag = "16")]
        Error(super::Error),
        #[prost(message, tag = "17")]
        Ok(super::Ok),
        #[prost(message, tag = "18")]
        Challenge(super::Challenge),
        #[prost(message, tag = "19")]
        Changes(super::Changes),
    }
}
/// First frame on a connection. The server answers with a `Challenge`, or with an `Error` if the frame is invalid.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Hello {
    /// Protocol version of the client. The server rejects a version other than its own with ERROR_CODE_BAD_REQUEST.
    #[prost(uint32, tag = "1")]
    pub protocol_version: u32,
    /// Random id of the client instance, e.g. one browser tab or worker. 1 to 64 bytes.
    #[prost(bytes = "vec", tag = "2")]
    pub instance_id: ::prost::alloc::vec::Vec<u8>,
    /// Algorithm and public key of the client's key pair. The client proves possession of the private key with a
    /// `Proof`. The server derives the subject from the public key. The subject determines which databases the
    /// connection can access. A client has no other way to select a subject.
    #[prost(enumeration = "SigAlg", tag = "3")]
    pub sig_alg: i32,
    /// 5 and 6 are reserved for an enrolment token and a second signature algorithm.
    #[prost(bytes = "vec", tag = "4")]
    pub public_key: ::prost::alloc::vec::Vec<u8>,
}
/// Answer to `Hello`, with the Hello's request_id. The client answers with a `Proof`.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Challenge {
    /// 32 random bytes. Valid for this login only.
    #[prost(bytes = "vec", tag = "1")]
    pub nonce: ::prost::alloc::vec::Vec<u8>,
    /// The server's configured identifier, normally its public WebSocket URL, e.g. "wss://vfs.example/v1/ws". It is
    /// part of the signed transcript. A client that compares it with the URL it connected to detects a challenge that
    /// another server relays. Browsers do not expose TLS channel binding, so this is the only binding available.
    /// sqlite-remote-vfs does not compare it; it expects a separate key for each server instead.
    #[prost(string, tag = "2")]
    pub server_id: ::prost::alloc::string::String,
    /// Deadline for the `Proof`, in milliseconds since the Unix epoch.
    #[prost(uint64, tag = "3")]
    pub expires_at_ms: u64,
}
/// Answer to `Challenge`. The server answers with `HelloOk`, or with an `Error` (ERROR_CODE_UNAUTHENTICATED), both
/// with the Proof's request_id.
///
/// `signature` is the signature over the following transcript. Each part is preceded by its length as a 4-byte
/// big-endian integer:
///
///    "sqlite-remote-auth-v1" || server_id || nonce || instance_id || sig_alg || public_key
///
/// sig_alg is the enum value as a 4-byte big-endian integer.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Proof {
    #[prost(bytes = "vec", tag = "1")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
}
/// Answer to a valid `Proof`, with the Proof's request_id. Completes the login and carries the server's limits.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HelloOk {
    /// Protocol version of the server.
    #[prost(uint32, tag = "1")]
    pub protocol_version: u32,
    /// Largest frame the server accepts, in bytes. The client splits a commit into parts that fit.
    #[prost(uint32, tag = "2")]
    pub max_frame_bytes: u32,
    /// Interval at which the client sends a `Ping` while it is otherwise idle, in milliseconds.
    #[prost(uint32, tag = "3")]
    pub ping_interval_ms: u32,
    /// Time after the last renewal from which another instance can acquire the lease without `takeover`, in
    /// milliseconds. Commits and pings renew the lease.
    #[prost(uint32, tag = "4")]
    pub lease_ttl_ms: u32,
}
/// Opens a database and acquires its lease, the exclusive right to commit to it. Answered with `Opened`.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Open {
    /// Name of the database within the subject. 1 to 128 bytes of UTF-8.
    #[prost(string, tag = "1")]
    pub db_id: ::prost::alloc::string::String,
    /// Page size of a new database. For an existing database it must be 0 or equal to the database's page size.
    #[prost(uint32, tag = "2")]
    pub page_size: u32,
    /// Creates the database if it does not exist or was deleted. Without it, such a database fails with
    /// ERROR_CODE_NOT_FOUND.
    #[prost(bool, tag = "3")]
    pub create_if_missing: bool,
    /// Acquires the lease even if another instance holds one that has not expired. Without it, the open fails with
    /// ERROR_CODE_LEASE_HELD in that case.
    #[prost(bool, tag = "4")]
    pub takeover: bool,
    /// Set only when reopening after a broken connection. Continues the previous lease instead of acquiring a new one.
    #[prost(message, optional, tag = "5")]
    pub resume: ::core::option::Option<Resume>,
}
/// The previous lease and state, for reopening after a broken connection.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Resume {
    /// lease_id and lease_epoch from the previous `Opened`. If the lease is no longer current, the open fails with
    /// ERROR_CODE_FENCED.
    #[prost(bytes = "vec", tag = "1")]
    pub lease_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub lease_epoch: u64,
    /// The last version the server acknowledged to this client.
    #[prost(uint64, tag = "3")]
    pub known_version: u64,
    /// commit_id of a commit that was sent but not acknowledged. Empty if there is none.
    #[prost(bytes = "vec", tag = "4")]
    pub pending_commit_id: ::prost::alloc::vec::Vec<u8>,
}
/// Answer to `Open`: the lease and the current state of the database.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Opened {
    #[prost(bytes = "vec", tag = "1")]
    pub lease_id: ::prost::alloc::vec::Vec<u8>,
    /// Fencing token. Every new lease has a higher epoch. A `Commit` must carry the current epoch, otherwise it fails
    /// with ERROR_CODE_FENCED.
    #[prost(uint64, tag = "2")]
    pub lease_epoch: u64,
    /// Current version. Every applied commit and every deletion increases it by 1.
    #[prost(uint64, tag = "3")]
    pub version: u64,
    #[prost(uint32, tag = "4")]
    pub page_size: u32,
    /// Length of the database file, in blocks.
    #[prost(uint64, tag = "5")]
    pub page_count: u64,
    /// commit_id of the last applied commit. A client whose commit was not acknowledged compares it with its own
    /// commit_id to find out whether the commit was applied.
    #[prost(bytes = "vec", tag = "6")]
    pub last_commit_id: ::prost::alloc::vec::Vec<u8>,
}
/// Requests blocks as of `version`. Either one range (`first_block` and `count`) or several (`ranges`). Answered with
/// one or more `Pages` frames.
///
/// Several ranges in one request are for catching up a local copy. The blocks changed by a series of commits are
/// spread across the file, and one request per range would cost one round trip each.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Fetch {
    #[prost(string, tag = "1")]
    pub db_id: ::prost::alloc::string::String,
    /// Must be the current version. Otherwise the request fails with ERROR_CODE_VERSION_CONFLICT.
    #[prost(uint64, tag = "2")]
    pub version: u64,
    /// One range: `count` blocks starting at `first_block`. Ignored if `ranges` is set.
    #[prost(uint64, tag = "3")]
    pub first_block: u64,
    #[prost(uint64, tag = "4")]
    pub count: u64,
    /// Several ranges, in ascending order and without overlap. At most 4096. Blocks that were never written are
    /// returned as zeros.
    #[prost(message, repeated, tag = "5")]
    pub ranges: ::prost::alloc::vec::Vec<Range>,
}
/// A range of consecutive blocks.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Range {
    #[prost(uint64, tag = "1")]
    pub first_block: u64,
    #[prost(uint64, tag = "2")]
    pub count: u64,
}
/// Blocks answering a `Fetch`, with the Fetch's request_id. The server sends the ranges in the requested order and
/// splits them across as many frames as needed. A frame never contains blocks from two ranges.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Pages {
    /// Index of the first block in this frame.
    #[prost(uint64, tag = "1")]
    pub first_block: u64,
    /// Consecutive blocks from `first_block`, each exactly page_size bytes.
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub blocks: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// True on the last frame of the answer.
    #[prost(bool, tag = "3")]
    pub last: bool,
}
/// Requests the indexes of all blocks changed since `from_version`. Answered with `Changes`.
///
/// Used to catch up a local copy that is a few commits behind. The client discards those blocks from the copy and
/// keeps the rest, instead of fetching the whole database.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Changed {
    #[prost(string, tag = "1")]
    pub db_id: ::prost::alloc::string::String,
    /// Version of the client's local copy. Must not be greater than the current version.
    #[prost(uint64, tag = "2")]
    pub from_version: u64,
}
/// Answer to `Changed`.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Changes {
    #[prost(uint64, tag = "1")]
    pub from_version: u64,
    /// The current version.
    #[prost(uint64, tag = "2")]
    pub to_version: u64,
    /// Indexes of all blocks written by any commit after `from_version`, ascending and without duplicates.
    #[prost(uint64, repeated, tag = "3")]
    pub blocks: ::prost::alloc::vec::Vec<u64>,
    /// False if the server's change log does not reach back to `from_version`, or the list does not fit in one frame.
    /// `blocks` is then empty and the client has to discard its local copy.
    #[prost(bool, tag = "4")]
    pub complete: bool,
}
/// One frame (part) of a commit: blocks changed by one or more SQLite transactions. The server applies a commit
/// atomically. Only the last part is answered, with `CommitAck` or `Error`. A refused part is answered with `Error`
/// at once.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Commit {
    #[prost(string, tag = "1")]
    pub db_id: ::prost::alloc::string::String,
    /// 16 random bytes, the same in every part. Makes a repeated commit idempotent: if the last applied commit has this
    /// id and the version is base_version + 1, the server answers with that version again.
    #[prost(bytes = "vec", tag = "2")]
    pub commit_id: ::prost::alloc::vec::Vec<u8>,
    /// Current lease epoch, otherwise ERROR_CODE_FENCED.
    #[prost(uint64, tag = "3")]
    pub lease_epoch: u64,
    /// Version the commit is based on. Must be the current version, otherwise ERROR_CODE_VERSION_CONFLICT.
    #[prost(uint64, tag = "4")]
    pub base_version: u64,
    /// Length of the database file after the commit, in blocks. Blocks at or beyond it are removed.
    #[prost(uint64, tag = "5")]
    pub page_count: u64,
    #[prost(message, repeated, tag = "6")]
    pub blocks: ::prost::alloc::vec::Vec<Block>,
    /// True if more parts of this commit follow.
    #[prost(bool, tag = "7")]
    pub more: bool,
    /// Number of this part within the commit, starting at 0. Part 0 starts a new commit and discards an incomplete one.
    /// Every further part must directly follow the previous part and repeat its commit_id, lease_epoch, base_version
    /// and page_count. Otherwise the server refuses it and discards the commit, so later parts cannot be applied on
    /// their own. This keeps a commit atomic although the client sends all parts without waiting for answers.
    #[prost(uint32, tag = "8")]
    pub part: u32,
}
/// One block of the database file.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Block {
    /// Byte offset in the file divided by page_size.
    #[prost(uint64, tag = "1")]
    pub index: u64,
    /// Exactly page_size bytes.
    #[prost(bytes = "vec", tag = "2")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// Answer to the last part of an applied `Commit`. The commit is durable when this is sent.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CommitAck {
    #[prost(bytes = "vec", tag = "1")]
    pub commit_id: ::prost::alloc::vec::Vec<u8>,
    /// Version after the commit.
    #[prost(uint64, tag = "2")]
    pub version: u64,
}
/// Releases the lease of a database immediately. Answered with `Ok`.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CloseDb {
    #[prost(string, tag = "1")]
    pub db_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub lease_epoch: u64,
}
/// Deletes a database: its blocks and its change log. Answered with `Ok`, also if the database does not exist or was
/// already deleted, so that a repeated request succeeds.
///
/// The database must not be open on this connection. The server keeps a record of the deleted database with its lease
/// epoch and version, and increases the epoch, so that no earlier lease can commit again. Opening the database again
/// with `create_if_missing` creates it empty with any page size; the epoch and the version continue from the deleted
/// database. Opening it without `create_if_missing` fails with ERROR_CODE_NOT_FOUND.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Delete {
    #[prost(string, tag = "1")]
    pub db_id: ::prost::alloc::string::String,
    /// Deletes even if another instance holds a lease that has not expired. That instance receives `LeaseRevoked`.
    /// Without it, the request fails with ERROR_CODE_LEASE_HELD in that case.
    #[prost(bool, tag = "2")]
    pub takeover: bool,
}
/// Keeps the connection open and renews the leases of all databases open on it. The server renews a lease only if
/// at least half of lease_ttl_ms has passed since its last renewal. Answered with `Pong`.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ping {
    /// Client clock in milliseconds. Returned unchanged in the `Pong`.
    #[prost(uint64, tag = "1")]
    pub client_time_ms: u64,
}
/// Answer to `Ping`.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Pong {
    #[prost(uint64, tag = "1")]
    pub client_time_ms: u64,
}
/// Answer to a request that returns no data, e.g. `CloseDb`.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Ok {}
/// Sent unprompted (request_id 0) when another instance has acquired the lease of a database open on this
/// connection. Delivery is not guaranteed. A client that missed it gets ERROR_CODE_FENCED on its next commit.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LeaseRevoked {
    #[prost(string, tag = "1")]
    pub db_id: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub new_lease_epoch: u64,
}
/// Answer to a failed request.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Error {
    #[prost(enumeration = "ErrorCode", tag = "1")]
    pub code: i32,
    /// Human-readable reason. For ERROR_CODE_INTERNAL it contains no details.
    #[prost(string, tag = "2")]
    pub detail: ::prost::alloc::string::String,
    /// Current version of the database. Set with ERROR_CODE_VERSION_CONFLICT.
    #[prost(uint64, tag = "3")]
    pub current_version: u64,
    /// Time the current lease was granted, in milliseconds since the Unix epoch. Set with ERROR_CODE_LEASE_HELD.
    #[prost(uint64, tag = "4")]
    pub lease_holder_since_ms: u64,
}
/// Signature algorithm of the client's key pair.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SigAlg {
    Unspecified = 0,
    Ed25519 = 1,
}
impl SigAlg {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SIG_ALG_UNSPECIFIED",
            Self::Ed25519 => "SIG_ALG_ED25519",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SIG_ALG_UNSPECIFIED" => Some(Self::Unspecified),
            "SIG_ALG_ED25519" => Some(Self::Ed25519),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ErrorCode {
    Unspecified = 0,
    /// Login failed: no valid `Proof`, an expired challenge, or a request before the login.
    Unauthenticated = 1,
    /// The database belongs to another subject.
    Forbidden = 2,
    /// The database does not exist or was deleted.
    NotFound = 3,
    /// Another instance holds a lease that has not expired.
    LeaseHeld = 4,
    /// The lease epoch is not the current one: another instance acquired the lease, or it was released.
    Fenced = 5,
    /// The request is based on a version other than the current one. See `Error.current_version`.
    VersionConflict = 6,
    /// The request is invalid and cannot succeed when repeated, e.g. a block of the wrong size, a block index at or
    /// beyond page_count, or a commit part that does not continue the pending commit.
    BadRequest = 7,
    /// The commit exceeds the server's size limit for one commit.
    TooLarge = 8,
    QuotaExceeded = 9,
    RateLimited = 10,
    /// Unexpected error on the server. Details are only in the server's log.
    Internal = 11,
}
impl ErrorCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ERROR_CODE_UNSPECIFIED",
            Self::Unauthenticated => "ERROR_CODE_UNAUTHENTICATED",
            Self::Forbidden => "ERROR_CODE_FORBIDDEN",
            Self::NotFound => "ERROR_CODE_NOT_FOUND",
            Self::LeaseHeld => "ERROR_CODE_LEASE_HELD",
            Self::Fenced => "ERROR_CODE_FENCED",
            Self::VersionConflict => "ERROR_CODE_VERSION_CONFLICT",
            Self::BadRequest => "ERROR_CODE_BAD_REQUEST",
            Self::TooLarge => "ERROR_CODE_TOO_LARGE",
            Self::QuotaExceeded => "ERROR_CODE_QUOTA_EXCEEDED",
            Self::RateLimited => "ERROR_CODE_RATE_LIMITED",
            Self::Internal => "ERROR_CODE_INTERNAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ERROR_CODE_UNSPECIFIED" => Some(Self::Unspecified),
            "ERROR_CODE_UNAUTHENTICATED" => Some(Self::Unauthenticated),
            "ERROR_CODE_FORBIDDEN" => Some(Self::Forbidden),
            "ERROR_CODE_NOT_FOUND" => Some(Self::NotFound),
            "ERROR_CODE_LEASE_HELD" => Some(Self::LeaseHeld),
            "ERROR_CODE_FENCED" => Some(Self::Fenced),
            "ERROR_CODE_VERSION_CONFLICT" => Some(Self::VersionConflict),
            "ERROR_CODE_BAD_REQUEST" => Some(Self::BadRequest),
            "ERROR_CODE_TOO_LARGE" => Some(Self::TooLarge),
            "ERROR_CODE_QUOTA_EXCEEDED" => Some(Self::QuotaExceeded),
            "ERROR_CODE_RATE_LIMITED" => Some(Self::RateLimited),
            "ERROR_CODE_INTERNAL" => Some(Self::Internal),
            _ => None,
        }
    }
}
